### ISSUE TITLE
More details for bundle watch

### ISSUE THREAD

**Issue by venelinn** [dowjones/gulp-bundle-assets#74]
Hi again !
I'm looking for more information how to setup the watcher.
So, I have 2 questions
This is my bundle.config.js
```
module.exports = {
    bundle: {
        c411: {
            scripts: [
                'resources/js/common/utils.js',
                'resources/js/common/userMenu.js',
                'resources/js/common/headerFooter.js',
                'resources/js/common.js'
            ],
            styles: [
                'resources/css/bootstrap.css',
                'resources/css/common.css'
            ],
            options: {
                rev: false
            }
        }
    }
};
```

I have another task for generation CSS from SCSS (before run bundle) using gulp-sass
```
gulp.task('styles', function() {
    return gulp.src(sassSources)
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(sass.sync())
        .pipe(autoprefixer())
        .pipe(gulp.dest('resources/css'));
});
gulp.task('bundle', ['styles'], function() {
    return gulp.src('./bundle.config.js')
    .pipe(bundle())
    .pipe(gulp.dest('resources/static'));
});
```
So, first question, is this the right way?
And the second one how to watch for changes without regenerating all assets over and over?

Let me know if you need more info!
Thanks!

**Comment by chmontgomery** [comment]
@venelinn Firstly, you can use gulp-bundle-assets to run your sass compilation so that you can create your entire css bundle in one go. [See the custom-transforms example on how to do this](https://github.com/dowjones/gulp-bundle-assets/tree/master/examples/custom-transforms#custom-transforms).

Secondly, you can use the built in `gbundle.watch` to only re-build the bundles that changed. [See this example for details](https://github.com/dowjones/gulp-bundle-assets/blob/master/examples/full/gulpfile.js#L26).

Let me know if that doesn't answer your questions.

**Comment by acheshkov** [comment]
Hi @chmontgomery,

 _gbundle_ is not  a part of library, is it ? it means that i have to copy all dependencies to get it work.
